-- Operator Intelligence V2 persistence schema (Postgres / Supabase ready)
create table if not exists investigations (id text primary key,name text not null,domain text default '',status text not null default 'Active investigation',summary text default '',created_at timestamptz default now(),updated_at timestamptz default now());
create table if not exists entities (id text primary key,investigation_id text not null references investigations(id) on delete cascade,label text not null,type text not null,subtitle text default '',confidence text not null default 'lead',x numeric default 0,y numeric default 0,details jsonb not null default '[]'::jsonb,created_at timestamptz default now());
create table if not exists relationships (id bigint generated always as identity primary key,investigation_id text not null references investigations(id) on delete cascade,from_entity text not null references entities(id) on delete cascade,to_entity text not null references entities(id) on delete cascade,label text not null,confidence text not null default 'lead',created_at timestamptz default now());
create table if not exists evidence (id text primary key,investigation_id text not null references investigations(id) on delete cascade,title text not null,source text not null,confidence text not null default 'lead',note text default '',created_at timestamptz default now());
create table if not exists timeline (id bigint generated always as identity primary key,investigation_id text not null references investigations(id) on delete cascade,event_date text not null,title text not null,body text default '',created_at timestamptz default now());
create table if not exists open_questions (id bigint generated always as identity primary key,investigation_id text not null references investigations(id) on delete cascade,question text not null,resolved boolean not null default false,created_at timestamptz default now());
create index if not exists entities_investigation_idx on entities(investigation_id);
create index if not exists relationships_investigation_idx on relationships(investigation_id);
create index if not exists evidence_investigation_idx on evidence(investigation_id);
