// Vendor signatures for marketing channels (client-safe: no network code).
export type ChannelGroup="Paid social"|"Search & shopping"|"Programmatic & native"|"TV & audio"|"Email & SMS"|"Affiliate & influencer"|"Direct mail"|"Marketplaces"|"Organic social";
export type ChannelSignal={channel:string;vendor:string;where:"site"|"gtm"};
export type ChannelScan={checkedAt:string;pages:string[];gtm:string[];signals:ChannelSignal[]};

// [channel, group, vendor, pattern]. Patterns match script hosts or vendor-specific globals, never generic words.
export const SIGNATURES:[string,ChannelGroup,string,RegExp][]=[
 ["Meta (Facebook/Instagram)","Paid social","Meta pixel",/connect\.facebook\.net\/[^"']*fbevents|fbq\(\s*['"]init|facebook_pixel|"facebook":\{"pixelId"|"facebookPixelId"/i],
 ["TikTok","Paid social","TikTok pixel",/analytics\.tiktok\.com|ttq\.load\(|pixelCode\\?"\s*:\s*\\?"[A-Z0-9]{15,}|"tiktokPixelId"/i],
 ["Pinterest","Paid social","Pinterest tag",/s\.pinimg\.com\/ct\/|pintrk\(|ct\.pinterest\.com|__pntr\b|tagID\\?"\s*:\s*\\?"26\d{11}\b/i],
 ["Snapchat","Paid social","Snap pixel",/sc-static\.net\/scevent|snaptr\(|tr\.snapchat\.com/i],
 ["Reddit","Paid social","Reddit pixel",/redditstatic\.com\/ads|rdt\(\s*['"]init|alb\.reddit\.com/i],
 ["X (Twitter)","Paid social","X pixel",/static\.ads-twitter\.com|twq\(\s*['"]|__twitter_website_tag/i],
 ["LinkedIn","Paid social","LinkedIn Insight",/snap\.licdn\.com|_linkedin_partner_id|__bzi\b/i],
 ["Google Ads / YouTube","Search & shopping","Google Ads tag",/["'\s(=]AW-\d{6,}|googleadservices\.com\/pagead\/conversion|__awct\b|__sp\b.*conversionId/i],
 ["Microsoft Ads (Bing)","Search & shopping","Microsoft UET",/bat\.bing\.com|uetq|__baut\b/i],
 ["AppLovin","Programmatic & native","AppLovin Axon",/applovin|axon\.ai\/|aplvn|Axon Pixel/i],
 ["Criteo","Programmatic & native","Criteo",/static\.criteo\.net|criteo\.com\/js|__crto\b/i],
 ["Google DV360 / CM","Programmatic & native","Floodlight",/fls\.doubleclick\.net|__fls\b|["']DC-\d{6,}/i],
 ["The Trade Desk","Programmatic & native","Trade Desk pixel",/js\.adsrvr\.org|insight\.adsrvr\.org/i],
 ["Amazon DSP","Programmatic & native","Amazon Ads tag",/amazon-adsystem\.com/i],
 ["Basis DSP","Programmatic & native","Basis pixel",/pixel\.sitescout\.com|basisPixel/i],
 ["Klickly","Programmatic & native","Klickly",/klickly\.com/i],
 ["StackAdapt","Programmatic & native","StackAdapt",/tags\.srv\.stackadapt\.com|saq\(/i],
 ["Taboola","Programmatic & native","Taboola",/cdn\.taboola\.com|_tfa\.push/i],
 ["Outbrain","Programmatic & native","Outbrain",/amplify\.outbrain\.com|obApi\(/i],
 ["NewsBreak","Programmatic & native","NewsBreak pixel",/newsbreak\.com\/[^"']*(?:pixel|tracking)|nbpix/i],
 ["SmartNews","Programmatic & native","SmartNews pixel",/smartnews-ads\.com/i],
 ["MGID","Programmatic & native","MGID",/jsc\.mgid\.com|mgid\.com\/(?:pixel|1\/)|_mgq\b/i],
 ["Revcontent","Programmatic & native","Revcontent",/revcontent\.com/i],
 ["Yahoo DSP / Native","Programmatic & native","Yahoo tag",/s\.yimg\.com\/wi\/ytc\.js|sp\.analytics\.yahoo\.com/i],
 ["Nativo","Programmatic & native","Nativo",/ntv\.io\/|nativo\.com/i],
 ["Dianomi","Programmatic & native","Dianomi",/dianomi\.com/i],
 ["AdRoll","Programmatic & native","AdRoll",/d\.adroll\.com|adroll_adv_id/i],
 ["Quora","Paid social","Quora pixel",/a\.quora\.com\/qevents|qp\(\s*['"]init/i],
 ["Nextdoor","Paid social","Nextdoor pixel",/ads\.nextdoor\.com|ndp\(\s*['"]init/i],
 ["Connected TV","TV & audio","MNTN",/px\.mountain\.com|dx\.mountain\.com/i],
 ["Connected TV","TV & audio","tvScientific",/tvscientific/i],
 ["Connected TV","TV & audio","Vibe",/s\.vibe\.co|vbpx\(/i],
 ["Connected TV","TV & audio","Tatari",/tatari\.tv|tatari\.js/i],
 ["TV","TV & audio","TVSquared / Innovid",/tvsquared\.com|innovid/i],
 ["Podcasts","TV & audio","Podscribe",/podscribe/i],
 ["Podcasts / audio","TV & audio","Claritas pixel",/trkn\.us|claritas/i],
 ["Podcasts / Spotify","TV & audio","Spotify pixel",/pixel\.byspotify\.com|spdt\(/i],
 ["Email","Email & SMS","Klaviyo",/static\.klaviyo\.com|klaviyo\.com\/onsite|_learnq/i],
 ["Email","Email & SMS","Omnisend",/omnisnippet|omnisend\.com/i],
 ["Email","Email & SMS","Mailchimp",/chimpstatic\.com/i],
 ["SMS","Email & SMS","Attentive",/cdn\.attn\.tv|attentivemobile/i],
 ["SMS","Email & SMS","Postscript",/postscript\.io/i],
 ["SMS","Email & SMS","Emotive",/emotiveapp|emotive\.io/i],
 ["SMS","Email & SMS","Recart",/recart\.com/i],
 ["Affiliates","Affiliate & influencer","impact.com",/impactcdn\.com|impact\.com\/|impactradius|ire\(\s*['"]identify/i],
 ["Affiliates","Affiliate & influencer","Refersion",/refersion\.com/i],
 ["Affiliates","Affiliate & influencer","ShareASale",/shareasale/i],
 ["Affiliates","Affiliate & influencer","Awin",/dwin1\.com|awin1\.com/i],
 ["Affiliates","Affiliate & influencer","CJ",/emjcd\.com|\.cj\.com\/|cjevent/i],
 ["Affiliates","Affiliate & influencer","Rakuten",/linksynergy|rakutenmarketing/i],
 ["Affiliates","Affiliate & influencer","Everflow",/everflow\.io|\bEF\.conversion/i],
 ["Affiliates","Affiliate & influencer","UpPromote",/uppromote/i],
 ["Affiliates","Affiliate & influencer","GoAffPro",/goaffpro/i],
 ["Influencers","Affiliate & influencer","Social Snowball",/socialsnowball/i],
 ["Influencers","Affiliate & influencer","Superfiliate",/superfiliate/i],
 ["Influencers","Affiliate & influencer","GRIN",/grin\.co\/|grin-sdk|grintrack/i],
 ["Influencers","Affiliate & influencer","Aspire",/aspireiq|aspire\.io/i],
 ["Influencers","Affiliate & influencer","Upfluence",/upfluence/i],
 ["Referrals","Affiliate & influencer","Friendbuy / ReferralCandy / Talkable",/friendbuy|referralcandy|talkable\.com/i],
 ["Direct mail","Direct mail","PostPilot",/postpilot/i],
 ["Direct mail","Direct mail","Poplar",/heypoplar|poplar\.studio/i],
];
export const GROUP_OF:Record<string,ChannelGroup>=Object.fromEntries(SIGNATURES.map(([c,g])=>[c,g]));

