import {Case} from "./types";
export const cases:Case[]=[
{id:"ultimapeak",name:"UltimaPeak",domain:"ultimapeak.com",status:"Active investigation",summary:"Supplement brand with a documented IP trail through Remo van der Heijden and an operational bridge through Dovcon B.V. Current legal wrapper: Wealth Innovations LLC.",nodes:[
{id:"up",label:"UltimaPeak",type:"brand",subtitle:"Supplement brand",x:420,y:235,confidence:"confirmed",details:["Domain: ultimapeak.com","Current legal wrapper: Wealth Innovations LLC","Dovcon B.V. appears in reported merchant descriptor"]},
{id:"remo",label:"Remo van der Heijden",type:"person",subtitle:"Operator / IP origin",x:95,y:80,confidence:"confirmed",details:["Filed EU ULTIMAPEAK trademark Feb 27, 2025","Historical co-owner of TravX","Director history through Dovcon structure"]},
{id:"brandon",label:"Brandon van Mierlo",type:"person",subtitle:"Associated operator",x:95,y:390,confidence:"strong",details:["Built TravX with Remo","Connected to Dovcon Holding 2 B.V.","Publicly operates a current supplement business with Remo"]},
{id:"dovcon",label:"Dovcon B.V.",type:"company",subtitle:"Ecommerce operating company",x:390,y:410,confidence:"strong",details:["KvK 89544838","Woerden, Netherlands","Reported UltimaPeak merchant descriptor"]},
{id:"wealth",label:"Wealth Innovations LLC",type:"company",subtitle:"U.S. legal / trademark entity",x:735,y:210,confidence:"confirmed",details:["Named in UltimaPeak legal materials","U.S. ULTIMAPEAK trademark applicant","Claims priority from Remo's EU filing"]},
{id:"travx",label:"TravX",type:"brand",subtitle:"Prior beauty brand",x:400,y:65,confidence:"confirmed",details:["Prior Brandon + Remo operation","Dovcon-linked ecommerce brand"]},
{id:"tm",label:"ULTIMAPEAK EU",type:"trademark",subtitle:"EU 019148862",x:730,y:65,confidence:"confirmed",details:["Filed Feb 27, 2025","Applicant: Remo van der Heijden"]}
],edges:[
{from:"remo",to:"tm",label:"FILED",confidence:"confirmed"},{from:"tm",to:"wealth",label:"FOREIGN PRIORITY",confidence:"confirmed"},{from:"wealth",to:"up",label:"LEGAL / IP",confidence:"confirmed"},{from:"dovcon",to:"up",label:"MERCHANT FOR",confidence:"strong"},{from:"brandon",to:"dovcon",label:"CORPORATE BRIDGE",confidence:"strong"},{from:"remo",to:"travx",label:"CO-OWNER",confidence:"confirmed"},{from:"brandon",to:"travx",label:"BUILT",confidence:"confirmed"},{from:"travx",to:"dovcon",label:"OPERATED VIA",confidence:"confirmed"}],
evidence:[
{id:"e1",title:"EU ULTIMAPEAK filing",source:"EU trademark record",confidence:"confirmed",note:"Remo personally filed the original ULTIMAPEAK mark on Feb 27, 2025."},
{id:"e2",title:"U.S. priority chain",source:"U.S. trademark record",confidence:"confirmed",note:"Wealth Innovations LLC's U.S. filing claims foreign priority from Remo's EU application."},
{id:"e3",title:"Dovcon merchant descriptor",source:"Merchant descriptor database",confidence:"strong",note:"Reported statement variation includes Dovcon B.V. + ultimapeak.com."},
{id:"e4",title:"Dovcon health/wellness hiring",source:"Historical job posting",confidence:"strong",note:"Dovcon recruited for health/wellness creative work two days after Remo's trademark filing."}],
timeline:[
{date:"2023",title:"Dovcon / TravX period",body:"Brandon and Remo are documented in the Dovcon/TravX operating history."},
{date:"Feb 27, 2025",title:"ULTIMAPEAK filed in EU",body:"Remo files EU application 019148862."},
{date:"Mar 1, 2025",title:"Dovcon health & wellness hiring",body:"Dovcon recruits creative talent for health/wellness content."},
{date:"Jun 11, 2025",title:"U.S. trademark filing",body:"Wealth Innovations LLC files ULTIMAPEAK in the U.S. claiming priority to Remo's EU application."},
{date:"2026",title:"Current operating footprint",body:"UltimaPeak remains active; Dovcon appears in reported merchant-processing descriptors."}],
openQuestions:["Identify beneficial owners / members of the Delaware Wealth Innovations LLC.","Resolve the additional manager/entity in Dovcon B.V.'s current structure.","Identify fulfillment and subscription infrastructure.","Search technical identifiers for sibling storefronts."]},
{id:"resilia",name:"Resilia",domain:"resilia.shop",status:"Mapped",summary:"Resilia's legal/IP trail points to Sack Consulting Inc., with substantial operational evidence connecting the brand to Incubator Lab and its ecommerce network.",nodes:[
{id:"r",label:"Resilia",type:"brand",subtitle:"Supplement brand",x:420,y:230,confidence:"confirmed",details:["resilia.shop","Terms name Sack Consulting Inc. d/b/a Resilia"]},
{id:"sack",label:"Sack Consulting Inc.",type:"company",subtitle:"Legal / trademark owner",x:710,y:225,confidence:"confirmed",details:["Owns RESILIA marks","Named contracting business"]},
{id:"john",label:"Johnathan P. Sack",type:"person",subtitle:"Officer / director",x:720,y:60,confidence:"confirmed",details:["CEO / Secretary / CFO / Director in public records"]},
{id:"inc",label:"Incubator Lab",type:"company",subtitle:"Operating organization",x:390,y:410,confidence:"strong",details:["Jobs explicitly name Resilia","QA role explicitly monitors resilia.shop"]},
{id:"ilan",label:"Ilan Mussaffi",type:"person",subtitle:"Incubator Lab CEO",x:90,y:410,confidence:"strong",details:["Publicly associated with Incubator Lab","Do not equate with proven Resilia equity ownership"]},
{id:"neuro",label:"Neuro Bella",type:"brand",subtitle:"Infrastructure overlap",x:90,y:120,confidence:"correlation",details:["Historical page reused Resilia support identifiers","Ownership not established"]}],
edges:[{from:"sack",to:"r",label:"LEGAL / IP OWNER",confidence:"confirmed"},{from:"john",to:"sack",label:"OFFICER",confidence:"confirmed"},{from:"inc",to:"r",label:"OPERATES / HIRES FOR",confidence:"strong"},{from:"ilan",to:"inc",label:"CEO",confidence:"confirmed"},{from:"neuro",to:"r",label:"SHARED INFRASTRUCTURE",confidence:"correlation"}],
evidence:[{id:"r1",title:"Resilia Terms",source:"First-party Terms",confidence:"confirmed",note:"Identifies Sack Consulting Inc. d/b/a Resilia."},{id:"r2",title:"Trademark portfolio",source:"U.S. trademark records",confidence:"confirmed",note:"Sack Consulting owns RESILIA marks."},{id:"r3",title:"Incubator Lab hiring",source:"Job postings",confidence:"strong",note:"Roles explicitly hire for Resilia and monitor resilia.shop."}],
timeline:[{date:"2024",title:"Claimed first use",body:"RESILIA filings claim first use beginning in 2024."},{date:"2025–2026",title:"Operating footprint expands",body:"Incubator Lab job and employee evidence directly references Resilia."},{date:"Aug 2026",title:"Trademark registrations",body:"RESILIA registrations mature in the U.S."}],openQuestions:["Determine the contractual/equity relationship between Sack Consulting and Incubator Lab.","Resolve Neuro Bella's ownership independently.","Map additional brands operated by the same Incubator Lab team."]},
{id:"lymphoria",name:"Lymphoria",domain:"lymphoria.co",status:"Mapped",summary:"Lymphoria traces to Looxe LLC / Looxe Limited Liability Company, with Hadia Saleh and Milad Saleh appearing as managers in public registration records and a documented predecessor relationship to Nature's Sunrise.",nodes:[
{id:"l",label:"Lymphoria",type:"brand",subtitle:"Lymphatic supplement",x:420,y:220,confidence:"confirmed",details:["lymphoria.co","Current legal policies and trademark records converge on Looxe"]},
{id:"looxe",label:"Looxe LLC",type:"company",subtitle:"Legal / IP entity",x:720,y:220,confidence:"confirmed",details:["Virginia LLC / Florida foreign registration","Trademark applicant"]},
{id:"hadia",label:"Hadia Saleh",type:"person",subtitle:"Manager",x:720,y:60,confidence:"confirmed",details:["Listed manager in Florida foreign LLC registration"]},
{id:"milad",label:"Milad Saleh",type:"person",subtitle:"Manager",x:720,y:400,confidence:"confirmed",details:["Listed manager in Florida foreign LLC registration"]},
{id:"nature",label:"Nature's Sunrise",type:"brand",subtitle:"Predecessor brand",x:100,y:220,confidence:"confirmed",details:["USPTO specimen states Nature Sunrise is now Lymphoria"]},
{id:"xiugui",label:"Xiugui Ma",type:"person",subtitle:"Prior trademark applicant",x:100,y:405,confidence:"confirmed",details:["Application later assigned to Looxe"]}],
edges:[{from:"looxe",to:"l",label:"LEGAL / IP",confidence:"confirmed"},{from:"hadia",to:"looxe",label:"MANAGER",confidence:"confirmed"},{from:"milad",to:"looxe",label:"MANAGER",confidence:"confirmed"},{from:"nature",to:"l",label:"REBRANDED TO",confidence:"confirmed"},{from:"xiugui",to:"looxe",label:"ASSIGNED MARK TO",confidence:"confirmed"}],
evidence:[{id:"l1",title:"Lymphoria Terms",source:"First-party policies",confidence:"confirmed",note:"Policies identify Looxe and current support identifiers."},{id:"l2",title:"Trademark specimen",source:"USPTO",confidence:"confirmed",note:"Specimen explicitly states Nature Sunrise is now Lymphoria."},{id:"l3",title:"Assignment trail",source:"Trademark assignment / TTAB record",confidence:"confirmed",note:"Looxe acquired the Xiugui Ma LYMPHORIA application."}],
timeline:[{date:"2025",title:"Nature's Sunrise",body:"Predecessor operation appears before Lymphoria."},{date:"Dec 2025",title:"Early LYMPHORIA filings",body:"Competing trademark applications begin."},{date:"Feb 2026",title:"Looxe files LYMPHORIA",body:"Looxe files its own application."},{date:"Aug 2026",title:"Assignment to Looxe",body:"Looxe acquires Xiugui Ma's application and is substituted in the TTAB proceeding."}],openQuestions:["Verify Virginia SCC entity history directly.","Determine whether additional Looxe consumer brands exist.","Separate shared ecommerce infrastructure from true sibling ownership."]}
];