import {Case} from "./types";
import {cases as seedCases} from "./data";

const hasDb=()=>Boolean(process.env.SUPABASE_URL&&process.env.SUPABASE_SERVICE_ROLE_KEY);
async function request(path:string,init?:RequestInit){const url=process.env.SUPABASE_URL;const key=process.env.SUPABASE_SERVICE_ROLE_KEY;if(!url||!key)throw new Error("Database is not configured");const r=await fetch(url+"/rest/v1/"+path,{...init,headers:{apikey:key,Authorization:"Bearer "+key,"Content-Type":"application/json",Prefer:"return=representation",...(init?.headers||{})},cache:"no-store"});if(!r.ok)throw new Error(await r.text());return r.status===204?null:r.json()}
export async function listInvestigations():Promise<Case[]>{if(!hasDb())return seedCases;const investigations=await request("investigations?select=*&order=updated_at.desc");if(!investigations.length)return seedCases;return Promise.all(investigations.map(async(i:any)=>{const [nodes,edges,evidence,timeline,questions]=await Promise.all([request(`entities?investigation_id=eq.${encodeURIComponent(i.id)}&select=*`),request(`relationships?investigation_id=eq.${encodeURIComponent(i.id)}&select=*`),request(`evidence?investigation_id=eq.${encodeURIComponent(i.id)}&select=*`),request(`timeline?investigation_id=eq.${encodeURIComponent(i.id)}&select=*&order=id.asc`),request(`open_questions?investigation_id=eq.${encodeURIComponent(i.id)}&resolved=eq.false&select=*`)]);return {id:i.id,name:i.name,domain:i.domain,status:i.status,summary:i.summary,nodes:nodes.map((n:any)=>({id:n.id,label:n.label,type:n.type,subtitle:n.subtitle,x:Number(n.x),y:Number(n.y),confidence:n.confidence,details:n.details||[]})),edges:edges.map((e:any)=>({from:e.from_entity,to:e.to_entity,label:e.label,confidence:e.confidence})),evidence,timeline:timeline.map((t:any)=>({date:t.event_date,title:t.title,body:t.body})),openQuestions:questions.map((q:any)=>q.question)} as Case}))}
export async function saveInvestigation(c:Case){if(!hasDb())throw new Error("SUPABASE_URL and SUPABASE_SERVICE_ROLE_KEY are required");await request("investigations?on_conflict=id",{method:"POST",headers:{Prefer:"resolution=merge-duplicates,return=representation"},body:JSON.stringify({id:c.id,name:c.name,domain:c.domain,status:c.status,summary:c.summary,updated_at:new Date().toISOString()})});for(const table of ["relationships","entities","evidence","timeline","open_questions"])await request(table+"?investigation_id=eq."+encodeURIComponent(c.id),{method:"DELETE"});if(c.nodes.length)await request("entities",{method:"POST",body:JSON.stringify(c.nodes.map(n=>({...n,investigation_id:c.id})))});if(c.edges.length)await request("relationships",{method:"POST",body:JSON.stringify(c.edges.map(e=>({investigation_id:c.id,from_entity:e.from,to_entity:e.to,label:e.label,confidence:e.confidence})))});if(c.evidence.length)await request("evidence",{method:"POST",body:JSON.stringify(c.evidence.map(e=>({...e,investigation_id:c.id})))});if(c.timeline.length)await request("timeline",{method:"POST",body:JSON.stringify(c.timeline.map(t=>({investigation_id:c.id,event_date:t.date,title:t.title,body:t.body})))});if(c.openQuestions.length)await request("open_questions",{method:"POST",body:JSON.stringify(c.openQuestions.map(question=>({investigation_id:c.id,question})))});return c}
export function databaseConfigured(){return hasDb()}


export async function listResearchJobs(investigationId:string){if(!hasDb())return [];return request("oi_research_jobs?investigation_id=eq."+encodeURIComponent(investigationId)+"&select=*&order=created_at.desc")}
export async function listResearchSources(investigationId:string){if(!hasDb())return [];return request("oi_sources?investigation_id=eq."+encodeURIComponent(investigationId)+"&select=*&order=retrieved_at.desc")}
export async function queueResearchJob(input:{investigationId:string;seedEntityId?:string|null;seedValue:string;seedType:string;maxDepth?:number}){const id="job_"+Date.now().toString(36);const rows=await request("oi_research_jobs",{method:"POST",body:JSON.stringify({id,investigation_id:input.investigationId,seed_entity_id:input.seedEntityId||null,seed_value:input.seedValue,seed_type:input.seedType,status:"queued",depth:0,max_depth:Math.max(1,Math.min(input.maxDepth||3,5)),provider:"pending",progress:0,message:"Queued for research",error:""})});return rows[0]}
export async function updateResearchJob(id:string,patch:Record<string,unknown>){const rows=await request("oi_research_jobs?id=eq."+encodeURIComponent(id),{method:"PATCH",body:JSON.stringify({...patch,updated_at:new Date().toISOString()})});return rows[0]}
